[tool.poetry]
name = "objectsync"
version = "0.3.2"
description = ""
authors = ["peterxcli <peterxcli@gmail.com>","eri24816 <a931eric@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
chatRoom = { git = "https://github.com/eri24816/ChatRoom.git", branch = "main" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
